### PR TITLE
Fixing issue #22

### PR DESCRIPTION
**Pull request by madness-inc**
Hi,

please check `MessageBirdServiceImpl.getErrorReport`, as I wasn't able to run the tests (didn't know which values to use for `messageBirdAccessKey` and `messageBirdMSISDN`).

Regards
Matthias

### CODE REVIEW

**Comment by madness-inc** [comment]
Hmm the build with JDK 6 failed because Jackson 2 requires Java 7.
Is it mandatory to support Java 6?
I wonder how the build could have passed before, since the already was a Jackson 2 dependency in use...

**Comment by cooldarkdryplace** [comment]
Thanks for your PR. Please give us some time to discuss this internally.
Cheers!

**Comment by madness-inc** [comment]
Note: Seems like `jackson-dataformat-csv` is not even needed to compile, so it could be removed.

**Comment by madness-inc** [comment]
Hi,

any News here?
How about releasing a 1.4 as a last version with Jackson 1 / Java 6 support and then continuing with a 2.0 including Jackson 2 and dropping Java 6 support?

Regards
Matthias

**Comment by cooldarkdryplace** [comment]
Hi Matthias.

We have discussed your changes. Looks like we are not ready to drop Java 6 support yet. 
We are going to add Java version info to user agent header, and this will give us more info about current versions in use. Issue you have raised also leads us to decision to officially declare what versions and how many of them we support. 

Thanks for your contribution! I will close this PR for now, but let's keep the Issue open.

Best from Amsterdam,
Andrii

**Comment by cooldarkdryplace** [comment]
@madness-inc Hello again. We are reopening this PR, going to drop Java 6 support. Please give us few days for tests/review.

**Comment by madness-inc** [comment]
Hi Andrii,

nice to hear that! Looking forward to the next release :-)

Regards
Matthias

**Comment by marcelcorso** [comment]
Hey @madness-inc! I have a few requests:

 * Can you please update the hardcoded version of the lib (jackson-databind-2.1.1.jar)  on the readme? 
 * Can you please remove the openjdk6 from `.travis.yml` ?
 * Can you please merge the upstream master to your clone/branch so that the tests for `oraclejdk7` pass? (we fixed this today) 

After this I think we are done. I just tried your branch and it looks 👍

**Comment by marcelcorso** [comment]
I'm closing this because I moved the code to another branch/pull request so I could finish it myself

**Comment by marcelcorso** [comment]
https://github.com/messagebird/java-rest-api/pull/25

**Comment by madness-inc** [comment]
Hi,
sorry for replying so late, have been really busy.
Thanks for taking over the necessary tasks!

Regards
Matthias

**Pull request closed without merging**
