### PR TITLE
Fix MessageBirdClient.updateConversation method.

### PR DESCRIPTION
**Pull request by RafeArnold**

### CODE REVIEW

**Comment by RafeArnold** [comment]
I noticed your client implementation for the [update conversation endpoint](https://developers.messagebird.com/api/conversations/#update-conversation-status) is sending incorrectly formed JSON. This pull request should resolve that.

@denizkilic you mentioned previously that you are moving away from sending real requests in your tests and only using mocks instead (https://developers.messagebird.com/api/conversations/#update-conversation-status). Although I appreciate that this is a simple and more reusable approach for unit tests, I think the benefits of testing against your real API should not be ignored. A test that sent a request to your real API would have picked up on this bug immediately. I am certainly not trying to encourage you to move away from mocks (as I think these are also important), but I believe _additional_ tests against your real API would also be extremely beneficial for spotting issues like this.

**Comment by denizkilic** [comment]
Hi @RafeArnold 

Thank you for noticing the bug and creating the PR. We will review it as soon as possible. 

About tests, unit tests are used to test methods, parameters for all edge cases. They are even more meaningful with TDD. However, real API calls should be tested somewhere else. Integration tests are best for it. We would like to create integration tests in the future on the client. 

In the current project, we do test real API calls locally before merging PRs. In the “examples” folder, there are classes to test endpoints. 

We always welcome issues/PRs if you notice any bug.

**Comment by RafeArnold** [comment]
> Hi @RafeArnold
> 
> Thank you for noticing the bug and creating the PR. We will review it as soon as possible.
> 
> About tests, unit tests are used to test methods, parameters for all edge cases. They are even more meaningful with TDD. However, real API calls should be tested somewhere else. Integration tests are best for it. We would like to create integration tests in the future on the client.
> 
> In the current project, we do test real API calls locally before merging PRs. In the “examples” folder, there are classes to test endpoints.
> 
> We always welcome issues/PRs if you notice any bug.

I agree fully. Thanks for the clarification.

I have added an example for the update conversation endpoint.

**Comment by denizkilic** [comment]
LGTM, example is tested

**Pull request merged**
